# This is a basic workflow to help you get started with Actions

name: Deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          path: main

      - uses: actions/checkout@v2
        with:
          path: prod
          ref: prod

      # Runs a single command using the runners shell
      - run: sudo apt update -y && sudo apt install nodejs -y
      - run: npm install -g yarn
      - run: cd main
      - run: yarn
      - run: yarn build
      - run: rm -rf ../prod/docs
      - run: mv build ../prod/docs
      - run: cd ../prod
      - run: git add docs
      - run: git config --global user.name "Github Actions"
      - run: git config --global user.email "nickpal+githubactions@nickpalenchar.com"
      - run: git commit -m "Deploy version 1.$GITHUB_RUN_NUMBER.0"
      - run: git push
